config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :pilots
root to: 'pilots#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
  
end

app/models/race.rb
class Race < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pilots_controller.rb
class PilotsController < ActionController::Base

  def pilot

  end

  def index
    @pilots = Pilot.all
  end

  def show
    @pilot = Pilot.find(params[:id])
  end

  def new
    @pilot = Pilot.new
  end

  def polarization

  end

  def create
    @pilot = Pilot.create(pilot_params)
    redirect_to root_path
  end

    def edit
      @pilot = Pilot.find(params[:id])
    end

    def update
      if @pilot.update(pilot_params)
        flash[:success] = "Hoorayy! Your pilot has been updated."
        redirect_to pilots_path
      else
        flash.now[:alert] = "Ohh no!! Update failed.  But go ahead and try again!"
        render :edit
      end
    end

      def destroy
        @pilot = Pilot.find(params[:id])
        @pilot.destroy
        redirect_to root_path
      end

      private
      def pilot_params
        params.require(:pilot).permit(:name, :last_name, :polarization)
      end
    end

app/controllers/race_controller.rb
class RaceController < ActionController::Base

  def race

  end

  def index
    @races = Race.all
  end

  def show
    @race = Race.find(params[:id])
  end

  def new
    @race = Race.new
  end

  def polarization

  end

  def create
    @race = Race.create(race_params)
    redirect_to root_path
  end

    def edit
      @race = Race.find(params[:id])
    end

    def update
      if @race.update(race_params)
        flash[:success] = "Hoorayy! Your race has been updated."
        redirect_to races_path
      else
        flash.now[:alert] = "Ohh no!! Update failed.  But go ahead and try again!"
        render :edit
      end
    end

      def destroy
        @race = Race.find(params[:id])
        @race.destroy
        redirect_to root_path
      end

      private
      def race_params
        params.require(:race).permit(:name, :last_name, :polarization)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/race_helper.rb
module RaceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FpvWizard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pilots/_form.html.erb
<%= simple_form_for @pilot do |f| %>
  <%= f.input :name, label: 'Name:    ', error: 'Name is required' %>
  <%= f.input :last_name, label: 'Last Name:    !', error: 'Last name is required' %>
  <%= f.select :polarization, ['Right-->', '<--Left']%>
  <%= f.button :submit %>
<% end %>

app/views/pilots/edit.html.erb
<h2>Edit Pilot</h2>

<%= render 'form' %>

<%= link_to 'Delete!', pilot_path(@pilot), method: :delete, class: 'delete' %>

app/views/pilots/index.html.erb
<h2>pilots <a href="/pilots/new">(+)</a></h2>

<ul>
  <% @pilots.each do |pilot| %>
    <li>
      <a href="/pilots/<%= pilot.id %>">
        <%= pilot.name %>
        <%= pilot.last_name %>
        <%= pilot.polarization %>
      </a>
    </li>
  <% end %>
</ul>

app/views/pilots/new.html.erb
<h1>New Pilot</h1>
<form class="pilot_form">
<%= render 'form' %>
</form>

app/views/pilots/show.html.erb
<h2><%= @pilot.name %> <a href="/pilots/<%= @pilot.id %>/edit">(edit)</a></h2>
<h4><%= @pilot.last_name %></h4>
<h4><%= @pilot.polarization %></h4>